### PR TITLE
Automatically add missing dependencies

### LINKED ISSUE #428: Add missing dependencies automatically on using `use <pkg>`
Based on https://github.com/brotzeit/rustic/releases/tag/3.3 where the following feature was introduced 

> `rustic-cargo-add-missing-dependencies`: add missing dependencies to Cargo.toml, works with lsp-mode and eglot

Is there a way to make it a variable which if true it'll be added automatically? I think lsp in C adds headers automatically when you use a function from un-included libraries.

Ideally when you do `use <something>;` just on that line. I think. Can't currently remember how lsp provides completions on use. But if we can modify it, the completions could be made with already available crates on top and also crates that can be added to Toml so if they're chosen it activates the add to toml function. Might have to use/update a list of available crates from cargo locally for that though.

If it becomes too complex or not possible (doubt that considering it's emacs) then doing it automatically on save is also fine.

### PR DESCRIPTION
**Pull request by brotzeit**
close #428

### CODE REVIEW

**Comment by brotzeit** [comment]
I have to find a way to avoid the noise when 'cargo add' is failing when the imported crate doesn't exist.

**Comment by brotzeit** [comment]
One downside:
When there are multiple unresolved imports and one of the crates doesn't exist, no dependencies will be added. We could only avoid this by adding the crates one by one. Don't know if it's worth the overhead.

**Review by Atreyagaurav — APPROVED** [review]

**Comment by Atreyagaurav** [comment]
Oh  I need to be one with write access to approve, sorry.

Anyway that downside is ok, since if there is/are unresolved imports we're not going to be able to compile that code anyway, and when it's resolved then all of them will be added to `Cargo.toml` right? Then it's not a problem at all.

**Comment by brotzeit** [comment]
> and when it's resolved then all of them will be added to Cargo.toml right?

As soon all dependencies can be found, they will be added.

**Pull request merged**
