### PR TITLE
Rustic doc filter updates

### PR DESCRIPTION
**Pull request by samhedin**
Cleaning up the filter a bit, and fixing https://github.com/brotzeit/rustic/pull/332
For https://github.com/brotzeit/rustic/issues/334

### CODE REVIEW

**Comment by samhedin** [comment]
The git history got a bit messed up, but there's a merge commit in there so I don't want to be rebasing all willy nilly, arguably I should have submitted the revert of https://github.com/brotzeit/rustic/pull/332 in a separate PR. @brotzeit how would you like me to remedy my sins?

**Comment by samhedin** [comment]
These are some initial updates for `rustic-doc`. I'll add more once school stops literally beating the crap out of me.

**Comment by brotzeit** [comment]
School sucks ;)

**Review by brotzeit — APPROVED** [review]

**Comment by samhedin** [comment]
Gotta get that bread (at some point in the future.)

**Pull request merged**
