### PR TITLE
use :stderr for formatting buffers

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by samhedin** [comment]
When I run `rustic-format-buffer` on an incorrectly formatted buffer, an empty buffer called `*rustfmt* shows up. I assume that the buffer that should show up is `*rustfmt-warnings*`? It also appears but in the background.

**Comment by brotzeit** [comment]
@samhedin should work now.

**Comment by samhedin** [comment]
Using it prints `rustic-format-buffer: No buffer named *rustfmt-warnings*`.

**Comment by brotzeit** [comment]
@samhedin can you please test it again. I don't see the problem...

**Comment by samhedin** [comment]
Running `rustic-format-buffer` on a buffer without syntax errors works great now! 
But when I try with this 
```rust
#![allow(unused_imports, unused_variables, dead_code)]
fn main() {
}}
}
```
The empty buffer `*rustfmt*` shows up. In the background, the filled buffer `*rustfmt-warnings*` also appears with the actual warning. 
```
error: unexpected closing delimiter: `}`
 --> <stdin>:3:2
  |
2 | fn main() {
  |           - this opening brace...
3 | }}
  | -^ unexpected closing delimiter
  | |
  | ...matches this closing brace


Process rustic-rustfmt-process stderr finished
```
Are you seeing different behavior? I should have been more clear about this, no idea why I didn't specify what issues I was having when formatting a correct vs incorrect buffer.

**Comment by brotzeit** [comment]
I just tried it with warnings and not with an error.

But I know what the issue is. I'll try to fix it.

**Comment by brotzeit** [comment]
Now I remember why I didn't use `err-buf` in the first place. It seems it's not possible to add a filter function for the process stderr output. I really like the colored output...

**Comment by samhedin** [comment]
Does this mean that you would like to keep the current behavior and that this PR should be closed?

**Comment by brotzeit** [comment]
I wonder how hard it would be to add this functionality and get it merged.

**Pull request closed without merging**
