### PR TITLE
iss-210: rustic-babel add crate features

### PR DESCRIPTION
**Pull request by DouglasGray**
Allow crate features to be specified with a `:features` header in the babel block

### CODE REVIEW

**Comment by brotzeit** [comment]
Thanks for adding tests, but bad timing with #219 ;)
I will take a look but I'm currently working on a feature for emacs-ng, so please give me some time to review both PRs and then we can discuss how we want to implement it.

**Comment by DouglasGray** [comment]
Spoilt for choice! And no worries, no rush at all.

**Comment by brotzeit** [comment]
Thanks!

**Comment by brotzeit** [comment]
@DouglasGray I just realized we forgot to document it in the readme. Want to finish your work ?

**Comment by DouglasGray** [comment]
Sorry, oversight on my part there. New PR [here](https://github.com/brotzeit/rustic/pull/221)

**Pull request merged**
