### PR TITLE
Fix `rustic-compilation-panic` regex

### LINKED ISSUE #573: compilation-error-regexp does not always match test outputs
I'm not totally sure when this changed, but the `compilation-error-regexp` defined by rustic no longer matches the the output when a test assertion fails.

My test output generally looks like this:

```
thread 'module::submodule::subsubmodule' panicked at lib/rs/tests/test-module/models/db-model.rs:454:5:
```

The value added for `rustic-panic` in `compilation-error-regexp-alist-alist` is currently:

```elisp
"thread '[^']+' panicked at '[^']+', \\([^\n]+\\):\\([0-9]+\\):\\([0-9]+\\)"
```

The inclusion of the `'[^']+', after "panicked at" is what seems to prevent the match.

I have worked around it locally by adding the following to my `use-package` config for `rustic`:

```elisp
(use-package rustic
  :hook
  :hook
  (rustic-cargo-test-mode
   . (lambda () (add-to-list 'compilation-error-regexp-alist
                             `(,(rx "thread '"
                                    (one-or-more (not "'"))
                                    "' panicked at "
                                    (group (one-or-more not-newline))
                                    ":"
                                    (group (one-or-more digit))
                                    ":"
                                    (group (one-or-more digit)))
                               1 2 3))))
```

which generates the regexp `"thread '[^']+' panicked at \\(.+\\):\\([[:digit:]]+\\):\\([[:digit:]]+\\)"`.

With this in place, jumping back and forth between tests in the rustic test output compilation buffer works again as expected, along with jumping directly to the failing test.

### PR DESCRIPTION
**Pull request by neosimsim**
Fix `rustic-compilation-panic` regex by removing ` '[^']+',`

Closes #573

### CODE REVIEW

**Comment by neosimsim** [comment]
I added the test in a separate commit, so the regression is easier. Unfortunately I cannot figure out why `compilation-num-errors-found` jumps from 0 to 2.

**Comment by neosimsim** [comment]
> I added the test in a separate commit, so the regression is easier. Unfortunately I cannot figure out why `compilation-num-errors-found` jumps from 0 to 2.

I suspected `rustic-panic` to be in `compilation-error-regexp-alist` twice, but that not the case

```
(rustic-panic rustic-info rustic-warning rustic-error)
```

**Comment by psibi** [comment]
Note about https://github.com/brotzeit/rustic/issues/566

**Comment by neosimsim** [comment]
> Note about #566

Oh my goodness. I totally missed that. Thanks for pointing that out @psibi

**Comment by neosimsim** [comment]
Closed in favor of emacs-rustic/rustic#31

**Pull request closed without merging**
