### PR TITLE
Improve cargo run functionality when used without comint

### PR DESCRIPTION
**Pull request by psibi**
This improves the plain cargo run functionality:

- Makes cargo run buffer non editable. The original behaviour is
retained when comint is enabled.
- Introduces rustic-run-arguments similar to rustic-test-arguments
- Binds the key 'g' for doing re-run in the cargo run buffer

Note: This functionality needs to be tested by people who use comint
functionality with rustic-mode (Although I don't understand it's
usecase since Rust doesn't have a REPL workflow)

### CODE REVIEW

**Comment by brotzeit** [comment]
> Although I don't understand it's
usecase since Rust doesn't have a REPL workflow

I think it's about user input for programs that open a prompt.

**Comment by psibi** [comment]
> I think it's about user input for programs that open a prompt.

Ah, I see. :-) I will try to document it in my upcoming MR then.

**Comment by psibi** [comment]
> What is the intention ?

This is my usecase: I have a non interactive console program which I'm protyping and want to do `cargo run` quite a bit. Just pressing `g` from the `cargo run` buffer is quite handy and this PR implements that kind of workflow.

> It seems many users that make use of this feature want to be able to send input. Do you think we should only allow editing in rustic-cargo-comint-run-mode ?

Agree. I have to play around with it to understand this usecase better. Worst case, I think an workflow facilitating both would be to do add a two key binding to `rustic-cargo-run-rerun`. 

I think as a next step, I can enable comint and `polymode` package and understand the workflow better and probably update the PR accordingly. WDYT ?

**Comment by psibi** [comment]
> What is the intention ?

This is my usecase: I have a non interactive console program which I'm protyping and want to do `cargo run` quite a bit. Just pressing `g` from the `cargo run` buffer is quite handy and this PR implements that kind of workflow.

> It seems many users that make use of this feature want to be able to send input. Do you think we should only allow editing in rustic-cargo-comint-run-mode ?

Agree. I have to play around with it to understand this usecase better. Worst case, I think an workflow facilitating both would be to do add a two key binding to `rustic-cargo-run-rerun`. 

I think as a next step, I can enable comint and `polymode` package and understand the workflow better and probably update the PR accordingly. WDYT ?

**Comment by brotzeit** [comment]
> Just pressing g from the cargo run buffer is quite handy and this PR implements that kind of workflow.

I could have figured this out myself =)

> Worst case, I think an workflow facilitating both would be to do add a two key binding to rustic-cargo-run-rerun.

IMO if users want a comint mode they should use a different mode. Most users don't need it and prefer being able to use shortcuts like in compilation mode.

So we probably should make it clear in the docs that the default is NOT comint and if they want to use it they have to use polymode with the rustic comint mode. I think it would be good to extend the "Cargo/Run" section in the readme and add headings for each mode and explain the differences. If you want to do it would be nice, but you don't have to.

**Comment by psibi** [comment]
> IMO if users want a comint mode they should use a different mode. Most users don't need it and prefer being able to use shortcuts like in compilation mode.

Agree! I will see if I can create something along those lines in the coming days. Thanks for the answers!

**Pull request merged**
