### PR TITLE
Use rust-mode as dependency

### LINKED ISSUE #129: Use rust-mode as dependency
@tarsius did some work on rust-mode to help with this. I will try to do this step by step and see how it works.

### PR DESCRIPTION
**Pull request by brotzeit**
Better late than never...

close #129

### CODE REVIEW

**Comment by brotzeit** [comment]
Feedback anybody ? @tarsius @samhedin

**Comment by brotzeit** [comment]
I will merge this now. If anybody notice issues please open a bug report.

**Comment by tarsius** [comment]
Now this is suddenly progressing very fast. :grinning:

This time around it might take me a day or two before I can take a look. :stuck_out_tongue:

**Comment by brotzeit** [comment]
I'm not really productive in the summer months. I wonder how people get anything done in countries with high temperatures the whole year, probably only with air conditioning =)

**Pull request merged**
