### PR TITLE
Rustic rustdoc

### PR DESCRIPTION
**Pull request by samhedin**
From https://github.com/brotzeit/rustic/issues/137
This is a first attempt at merging in rustdoc. I have purposefully not changed much so details can be discussed.

* The prefix name `rustdoc` is still used everywhere. Should it be changed to `rustic` or something else? 
* In the thread @brotzeit mentions making this optional - how would that work? (This is my first time writing a package so still new to this). The way it is now, `rustdoc-mode` is available but not automatically enabled at any point when you install `rustic`, so the user has to activate the minor mode themselves. 

Feedback welcome!

### CODE REVIEW

**Comment by brotzeit** [comment]
Sorry, I forgot to finish this because I've been trying to get remacs working again. I will finish this the next days.

**Comment by brotzeit** [comment]
Let's merge this ok ?

**Comment by brotzeit** [comment]
@samhedin it would be great if you are motivated to help me as collobarator.

**Comment by samhedin** [comment]
@brotzeit It should be ready to merge now! I still feel new to all of this, but I am motivated to help in any way I can.

**Comment by brotzeit** [comment]
> @brotzeit It should be ready to merge now! I still feel new to all of this, but I am motivated to help in any way I can.

Thanks!

However most features are provided by lsp. If you are interested in improving your elisp skills and want to help beyond rustic, I would suggest that you join the lsp-mode channel. lsp-mode and lsp-ui are crucial for most rustic users and by now the community around the organization has become quite active and it's really fun to participate. If you want to join the project, just ask yyoncho.

**Pull request merged**
