### PR TITLE
crate version should be a string

### PR DESCRIPTION
**Pull request by 0atman**
removed number-to-string

### CODE REVIEW

**Comment by samhedin** [comment]
Apologies if I'm a bit out of the loop, but I'm giving it a try anyway.
When running the first snippet posted in https://github.com/brotzeit/rustic/issues/176 I get `rustic-babel-cargo-toml: Wrong type argument: numberp, 0\.2\.22`
``` rust
#+begin_src rust :crates '((time . 0.2.22))
// cargo-deps: time
extern crate time;
fn main() {
    println!("{}", time::now().rfc822z());
}
#+end_src
```
Is this working for you?

**Comment by 0atman** [comment]
I fully don't expect my code to work, as I'm not an elisp dev, nor do I know how to run it.
But the semver should be a string in your example. That's what I hoped my fix would support.
`0.2.22` isn't valid syntax, numerically speaking, right? :grin:

**Comment by samhedin** [comment]
Of course, got it. `rustic-test-babel-crate` fails now, but it should not be too bad to fix. If you can update the test accordingly, I say this looks good to merge!

**Comment by brotzeit** [comment]
I think it's better to keep things backwards compatible. Can you guys please take a look at #181

**Comment by brotzeit** [comment]
@0atman thanks for your help. Next time we will guide you to the solution and merge your PR.

**Pull request closed without merging**
