### PR TITLE
fix auto format on remote buffers

### LINKED ISSUE #241: Can't format remote buffers
If I open a TRAMP buffer to a remote `.rs` file, `rustic-format-file` fails with an error like:

```
Error: file `/ssh:<remote>:<path>/src/main.rs` does not exist
```

`rustic-format-buffer` works fine. 

Unsure why, but `rustic-before-save-hook` uses `rustic-format-file` instead of `rustic-format-buffer`. This leads to many annoying popups on remote buffers, since I have formatting configured to run on each save.

A quick solution is to replace `rustic-format-file`with `rustic-format-buffer` in `rustic-before-save-hook`.

### PR DESCRIPTION
**Pull request by dangirsh**
Fixes #241

### CODE REVIEW

**Comment by brotzeit** [comment]
Thanks for opening the pull request. But I just realized we assume that rustfmt is installed locally. Do you think we should rather try to run rustfmt on the remote host ?

**Comment by dangirsh** [comment]
Yes, I noticed that too. I had to disable auto-formatting, since my
channels / architectures on the local and remote don't match.

**Comment by brotzeit** [comment]
FTR we need to use something like `shell-command-to-string` in order to run rustfmt remotely.

**Comment by brotzeit** [comment]
Fixed in https://github.com/brotzeit/rustic/commit/979a3e0034f9ffd773b0b33ff2332f859f5538c8

**Pull request closed without merging**
