### PR TITLE
rustic-doc-setup conversion error

### PR DESCRIPTION
**Pull request by tpeacock19**
I'm getting the below error when trying to use `rustic-doc-setup`. I imagine that there may be an issue with the lua script, but perhaps its something on my side as well. I'm not familiar enough with lua myself, unfortunately.

<details>
<summary>
Error message when running `rustic-doc-setup`
</summary>

```sh
Generating org files in: /home/user/.local/share/emacs/rustic-doc/std
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 27 column 150
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 48 column 166
[WARNING] Duplicate identifier 'blanket-implementations' at input line 118 column 2790
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 892 column 166
[WARNING] Duplicate identifier 'blanket-implementations' at input line 991 column 3225
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 1366 column 166
[WARNING] Duplicate identifier 'blanket-implementations' at input line 1406 column 15592
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 1320 column 166
[WARNING] Duplicate identifier 'blanket-implementations' at input line 1423 column 2692
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 66 column 150
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 712 column 166
[WARNING] Duplicate identifier 'blanket-implementations' at input line 839 column 8591
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 1694 column 166
[WARNING] Duplicate identifier 'blanket-implementations' at input line 1847 column 6781
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'variants' at input line 8 column 137
[WARNING] Duplicate identifier 'trait-implementations' at input line 14 column 140
[WARNING] Duplicate identifier 'blanket-implementations' at input line 18 column 3799
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 2 column 150
[WARNING] Duplicate identifier 'blanket-implementations' at input line 3 column 2317
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 33 column 166
[WARNING] Duplicate identifier 'blanket-implementations' at input line 35 column 2244
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[..............................................]
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 4 column 150
[WARNING] Duplicate identifier 'blanket-implementations' at input line 134 column 3171
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 4 column 150
[WARNING] Duplicate identifier 'blanket-implementations' at input line 134 column 4786
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'trait-implementations' at input line 3 column 150
[WARNING] Duplicate identifier 'blanket-implementations' at input line 134 column 4221
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
[WARNING] Duplicate identifier 'associated-types' at input line 135 column 135
[WARNING] Duplicate identifier 'required-methods' at input line 136 column 141
[WARNING] Duplicate identifier 'provided-methods' at input line 159 column 141
[WARNING] Duplicate identifier 'implementors' at input line 1925 column 11836
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
	while retrieving list
```
</details>

### CODE REVIEW

**Comment by brotzeit** [comment]
Also works for me, thanks!

@samhedin how much work do you think it would need to dynamically include additional rust docs ?

**Comment by brotzeit** [comment]
It would be nice if I could run `rustic-doc-setup` in a repo looking up dependencies and add the docs.

**Comment by samhedin** [comment]
> It would be nice if I could run `rustic-doc-setup` in a repo looking up dependencies and add the docs.

Have you tried `rustic-doc-convert-current-package`? Maybe it needs a rename.

**Review by samhedin — APPROVED** [review]

**Comment by brotzeit** [comment]
> Have you tried rustic-doc-convert-current-package? If I understand you correctly, that's what it does :)

Nice =)

**Comment by brotzeit** [comment]
@samhedin I think it makes sense to run `rustic-doc-convert-current-package` by default when calling `rustic-doc-setup`. Or are there any reasons why we should keep it this way ?

**Comment by samhedin** [comment]
> @samhedin I think it makes sense to run `rustic-doc-convert-current-package` by default when calling `rustic-doc-setup`. Or are there any reasons why we should keep it this way ?

Agreed. https://github.com/brotzeit/rustic/pull/333

**Comment by samhedin** [comment]
I see now that these are not equivalent. `pandoc.Null != null`. returning `null` leaves the element unchanged, returning `pandoc.Null` removes the element. This change needs to be reverted, and we need to figure out something else.

**Comment by tpeacock19** [comment]
I've found that if you want to delete an element you need to return an empty list https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md#lua-filter-structure

There's an example [here](https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md#modifying-pandocs-manualtxt-for-man-pages) where footnote elements are removed. So I believe replacing `pandoc.Null` with `{}` will work. I've tested locally, However I'm not certain what I should be looking for to be replaced.

**Comment by samhedin** [comment]
> I've found that if you want to delete an element you need to return an empty list https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md#lua-filter-structure
> 
> There's an example [here](https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md#modifying-pandocs-manualtxt-for-man-pages) where footnote elements are removed. So I believe replacing `pandoc.Null` with `{}` will work. I've tested locally, However I'm not certain what I should be looking for to be replaced.

Can't believe I've missed that all this time (well, since `pandoc.Null` worked before I must have read it quickly ones then went on with my life). I made the change here: https://github.com/brotzeit/rustic/pull/339

**Pull request merged**
