### PR TITLE
enable automatic reloading of rust-analyzer when Cargo.toml changed

### PR DESCRIPTION
**Pull request by brotzeit**
#322

### CODE REVIEW

**Comment by brotzeit** [comment]
I guess we also have to check if there's a running server.

**Comment by flodiebold** [comment]
rust-analyzer can already reload the workspace if it is notified about changes in Cargo.toml. If that somehow doesn't work, I think it'd be a much better idea to fix that instead of putting in a workaround that results in worse user experience.

**Comment by brotzeit** [comment]
> rust-analyzer can already reload the workspace if it is notified about changes in Cargo.toml. 

And how does this currently happen when using lsp-mode ?

**Comment by flodiebold** [comment]
It is supposed to happen through the LSP file watching mechanism; rust-analyzer registers file watches including Cargo.toml, and when it receives a `didChangeWatchedFiles` notification about these files, it reloads the workspace.

**Comment by brotzeit** [comment]
Makes sense. I'll ensure that it really doesn't work and open an lsp-mode issue instead. Thanks for your help!

**Pull request closed without merging**
