### PR TITLE
No longer depend on async and projectile

### PR DESCRIPTION
**Pull request by tarsius**
Don't depend on `async` because doing so is completely unnecessary and don't depend on `projectile` because it should not be forced on users for the sake of some minor functionality (which we can also have without using `project` instead).

### CODE REVIEW

**Comment by brotzeit** [comment]
Thanks, I'll try to fix the text.

**Comment by brotzeit** [comment]
It seems the buffers aren't reverted.

**Comment by tarsius** [comment]
Sorry about that. I've pushed a fixed version.

Sadly `project--buffer-list` has to be wrapped.

**Comment by tarsius** [comment]
There was one more problem as I've been told by the tests.
I fixed it and now the tests are... gone?
Anyways. Please have another look.

**Comment by brotzeit** [comment]
Yeah travis is the problem. I will run the tests manually for now.

**Comment by tarsius** [comment]
> Yeah travis is the problem.

I'll probably have to deal with that soon too. :frowning_face:

**Comment by brotzeit** [comment]
:/

**Comment by brotzeit** [comment]
Oh nice green :+1:

**Comment by tarsius** [comment]
Sadly that required backporting. It's weird these things didn't exist until now.

**Pull request merged**
