### PR TITLE
Expired Elpa Keys

### PR DESCRIPTION
**Pull request by dickmao**
cf melpa/melpa#6462

The elpa key expiration has wrought havoc among elisp repos that actually conduct proper testing, proving once again that no good deed goes unpunished.

### CODE REVIEW

**Comment by brotzeit** [comment]
Wow, thanks! I will take a look at it and try to fix the tests.

**Comment by dickmao** [comment]
The failures are due to my removing `cargo install --force rustfmt-nightly`.  That particular invocation seems compile the universe all over again (taking about 12 minutes).

I don't understand the rust toolchain enough to do this correctly.  Today was the first time I installed rust on my laptop.

**Comment by brotzeit** [comment]
Nice!

**Comment by dickmao** [comment]
> `all` doesn't do what it used to do: generate the `*.elc` files.

In #97, I restore that behavior.  To explain, I like `make` merely to verify the code compiles (ideally without warnings, which this particular project cannot vouch for).  Having `make` leave behind `.elc` files seems unnecessary and potentially dangerous.  The unintended consequences of stale byte-compiled elc files are widely felt by unsuspecting emacs devotees.

**Comment by phillord** [comment]
> Also why is the `EMACS=$(EMACS)` thing needed?

I use that trick a lot. You can reset `EMACS` to be what ever you need this way without changing the make file.

For instance, m-buffer uses this.

https://github.com/phillord/m-buffer-el/blob/master/Makefile

**Comment by dickmao** [comment]
Well, in my case it wasn't strictly needed (I suspect I copied it from somewhere else).  I had fixed it in #97 .

If the env variable EMACS is exogenously set outside make, then it naturally flows through to cask.  If it's not set, cask assumes EMACS is unversioned "emacs".  So in both cases, explicit assignment of `EMACS=$(EMACS)` is redundant.

You might have a recipe command that isn't cask which requires the env variable EMACS to be set, so such an assignment may have its uses.  But I see this thing almost always with cask, and it's superfluous.

**Comment by phillord** [comment]
Yep, I normally use a "makefile-local" which I include and set my defaults up there, then conditionally include this. Allows me to set defaults without inflicting them on anyone else.

**Pull request merged**
